### ISSUE TITLE
Focus mode or One Group only mode

### ISSUE THREAD

**Issue by zwuv** [r3pr3ss10n/Telegram#1]
Hi, is there any way to display one group as the whole interface of Telegram app. 

For focusing on one group only, after login. The interface will be a Group(with topics) as the entire interface of the app. Then when one don't want to be in focus mode, an extra toggle in group hamburger/3 dots menu will be having an option of "Focus mode OFF" to exit the interface.

If you don't want this feature, please let me know how can learn to make such changes by myself. I primarily want to learn to modify the UI or ux only. 
PS: I am not a Java developer.

**Comment by r3pr3ss10n** [comment]
Hello. Never thought about such a thing, sorry. As an idea you can hide 'arrow back' button from ActionBar when 'focus mode' is activated. And also disallow back gesture of Android - https://stackoverflow.com/questions/73337457/android-disable-swipe-to-previous-screen. 

Not going to implement that, this client made for myself and i'm not taking feature requests.
